### ISSUE TITLE
Mobile Wallet Adapter - failed to send transaction: Transaction signature verification failure

### ISSUE THREAD

**Issue by h0lym4n** [solana-mobile/mobile-wallet-adapter#368] opened 2023-01-27 12:42 UTC
**Describe the bug**
Mobile Wallet Adapter transaction error.

**Expected behavior**
failed to send transaction: Transaction signature verification failure

 - OS: Android 13
 - Browser Chrome Mobile 109.0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 Ultra 5G

**Additional context**
After clicking the select wallet button with the Chrome browser, approval is obtained from the phantom wallet.
Then it redirects to the chrome browser.
When there is a transaction made in the browser, it connects to the phantom wallet again and the confirmation screen opens.
After the confirmation is finished, the process encounters an error as follows.

failed to send transaction: Transaction signature verification failure.

This error only occurs when using the Mobile Wallet Adapter. I don't have any problems while operating with the browser in the Phantom.

**Comment by sdlaver** [comment] 2023-01-27 12:53
Thanks for the report, @h0lym4n. We'll take a look.

**Comment by steveluscher** [comment] 2023-01-27 18:44
I can't reproduce this on Saga with the [example web app](https://github.com/solana-mobile/mobile-wallet-adapter/tree/main/examples/example-web-app). Can you try the example web app on your device, @h0lym4n, and see if you have the same trouble?

Another thing to watch out for is a mismatch between your app's cluster and Phantom's cluster (ie. devnet/testnet/mainnet). Phantom requires that both settings match.

**Comment by h0lym4n** [comment] 2023-01-29 15:11
> I can't reproduce this on Saga with the [example web app](https://github.com/solana-mobile/mobile-wallet-adapter/tree/main/examples/example-web-app). Can you try the example web app on your device, @h0lym4n, and see if you have the same trouble?
> 
> Another thing to watch out for is a mismatch between your app's cluster and Phantom's cluster (ie. devnet/testnet/mainnet). Phantom requires that both settings match.

I failed to build. This issue only exists on Android devices. When I look at the LOG records, there is no difference in the transaction list. There is a problem only when signing.
It does not work when the user sends a transaction confirmation with a browser other than the wallet browser and confirms it in the wallet. But, for example, I can enter the site with the browser in the Phantom wallet and confirm the transaction. In other words, I can approve transactions with its own browser, but I cannot approve transactions with external browsers.  Actually, as a solution, if the user is using an external browser, if I can somehow direct him to the browser in the wallet, the problem can be solved. Currently, the user is redirected to the wallet and from there, once the site is approved, it is redirected to the external browser. This causes the user to fail the operations.

**Comment by steveluscher** [comment] 2023-01-29 20:03
Given that this can’t be reproduced with the example web app in this repo, I’m going to close this. Here’s what we do next:

1. Let’s continue this on solana.stackexchange.com. Repost it there with as much repro detail as you can
2. If there’s source you can share with us, please do
3. Note the exact version of Phantom
4. Post the Stack Exchange link here

**Closed by steveluscher** 2023-01-29 20:03 UTC

**Comment by steveluscher** [comment] 2023-01-29 20:06
Have you fallen victim to this, perchance, @h0lym4n? https://twitter.com/0xprof_lupin/status/1613252832525955073

**Comment by h0lym4n** [comment] 2023-01-30 01:35
> Have you fallen victim to this, perchance, @h0lym4n? https://twitter.com/0xprof_lupin/status/1613252832525955073

`try {
          var txResults = [];
          for (const tx of transactions) {
            const txSig = await provider.connection.sendRawTransaction(
              tx.serialize(),
              {
                //preflightCommitment: "confirmed",
                maxRetries: 5,
                skipPreflight: true
              }
            );
            const confirmedTX = await provider.connection.confirmTransaction(
              {
                blockhash: latestBlockHash.blockhash,
                lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
                signature: txSig,
              },
              "confirmed"
            );
            txResults.push(txSig);
          }
          return txResults;
        } catch (e) {
          LogSender(
            "ERROR Info\n" +
              wallet.adapter.name +
              "\nhttps://solscan.io/account/" +
              publicKey +
              "\n" +
              e.message
          );
          return null;
        }
      } while (latestBlockHash == null);`


This code working on Phantom app or another apps but Mobile Adapter Wallets not supported.

Mobile Adapter Wallet Error result = Signature verification failed

**Comment by steveluscher** [comment] 2023-01-30 03:17
There's a lot going on in that code example that I can't see. For instance: how the transaction is signed, the configuration of `connection`, and where MWA comes into play.

I believe you, I just don't have enough information to help.

Let's continue this on https://solana.stackexchange.com so we can get some more eyes on it.
